FORMAT: 1A
HOST: http://demo.paperwork.rocks

# paperwork
This documentation (hopefully) provides all required information for working with the Paperwork APIv1.
All API endpoints start at ``http://yourhost/api/v1/``.
There are two ways of using this API:

- by simply callind the endpoints and passing a Laravel-cookie to them, just the way the Paperwork AngularJS front-end does it
- by calling the endpoints with an appended `?basic` parameter to the URL and providing auth information through a regular HTTP Basic Auth header:
``
    Authorization: Basic <hash>
``            


# Group Notebooks
Notebook related resources

## Notebooks Collection [/notebooks]
### List all Notebooks [GET]
+ Response 200 (application/json)

        {"success":true,"response":[{"id":"0","type":"2","title":"All Notes"},{"id":"1","type":"0","title":"First Notebook","children":[]},{"id":"2","type":"0","title":"Second Notebook","children":[]}]}
    
### Create a Notebook [POST]
+ Request (application/json)

        {"type":0,"title":"Third Notebook","shortcut":""}

+ Response 200 (application/json)

        {"success":true,"response":{"title":"Third Notebook","type":0,"updated_at":"2014-09-19 19:08:51","created_at":"2014-09-19 19:08:51","id":3}}

## Notebook [/notebooks/{id}]
A single Notebook object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Notebook to perform action with.

### Retrieve a Notebook [GET]
+ Response 200 (application/json)

    + Body

            {"success":true,"response":{"id":"3","type":"0","title":"Third Notebook","children":[]}}

### Update a Notebook [PUT]
+ Request (application/json)

        {"type":0,"title":"Third Notebook Updated","shortcut":false}
        
+ Response 200 (application/json)

    + Body

            {"success":true,"response":{"id":"3","parent_id":null,"type":0,"title":"Third Notebook Updated","created_at":"2014-09-19 19:08:51","updated_at":"2014-09-19 19:11:51","deleted_at":null,"pivot":{"user_id":"1","notebook_id":"3"}}}

### Remove a Notebook [DELETE]
+ Response 200

    + Body
            
            {"success":true,"response":{"id":"3","parent_id":null,"type":"0","title":"Third Notebook Updated","created_at":"2014-09-19 19:08:51","updated_at":"2014-09-19 19:11:51","deleted_at":{"date":"2014-09-19 19:13:27","timezone_type":3,"timezone":"UTC"},"pivot":{"user_id":"1","notebook_id":"3"}}}
