db:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_USER: paperwork
    MYSQL_PASSWORD: paperwork
    MYSQL_DATABASE: paperwork
  ports:
    - "3306:3306"
web:
  build: ./frontend
  ports:
    - "8080:80"
  links:
    - db
  command: /app/docker-runner.sh
